# Generated by Django 4.2.5 on 2025-02-11 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "block_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("block_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "District_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("District_name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GramPanchayat",
            fields=[
                (
                    "gp_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("gp_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "District",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps",
                        to="api_nursery.district",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps",
                        to="api_nursery.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plant_List",
            fields=[
                (
                    "Plant_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("Specis", models.CharField(max_length=255)),
                ("Plant_Name", models.CharField(max_length=255)),
                ("Plant_Name_hindi", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NurseryDetails",
            fields=[
                ("nursery_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nursery_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[("private", "1"), ("government", "2")],
                        default="government",
                        max_length=10,
                    ),
                ),
                ("image_nursery", models.ImageField(upload_to="nursery_images/")),
                ("total_quantity_of_plants", models.IntegerField()),
                ("total_type_of_plants", models.IntegerField()),
                ("asfs_no", models.CharField(blank=True, max_length=255, null=True)),
                ("khasra_no", models.CharField(blank=True, max_length=255, null=True)),
                ("location_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_long", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "location_filling",
                    models.CharField(
                        choices=[("auto", "Auto"), ("manual", "Manual")],
                        default="auto",
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "depart_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurseries",
                        to="api.gov_department",
                    ),
                ),
                (
                    "gram_panchayat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurseries",
                        to="api_nursery.grampanchayat",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurseries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListOfPlantsInNursery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NameOfPlant", models.CharField(max_length=255)),
                ("quantity_of_plants", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "NurseryId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_list",
                        to="api_nursery.nurserydetails",
                    ),
                ),
                (
                    "plant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurseries",
                        to="api_nursery.plant_list",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="block",
            name="District",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="api_nursery.district",
            ),
        ),
    ]
