# Generated by Django 4.2.5 on 2025-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockList",
            fields=[
                (
                    "BLOCK_C",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("BLOCK_N", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="DistrictList",
            fields=[
                (
                    "DISTRICT_C",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("DISTRICT_N", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="GpFinalList",
            fields=[
                (
                    "GP_FINAL_C",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("GP_FINAL_N", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ShortDatabase_chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id_code", models.CharField(max_length=35)),
                ("value", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ShortDatabase_deTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id_code", models.CharField(max_length=35)),
                ("department_name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ShortDatabase_normal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DISTRICT_C", models.CharField(max_length=15)),
                ("DISTRICT_N", models.CharField(max_length=35)),
                ("BLOCK_C", models.CharField(max_length=15)),
                ("BLOCK_N", models.CharField(max_length=35)),
                ("GP_FINAL_C", models.CharField(max_length=15)),
                ("GP_FINAL_N", models.CharField(max_length=35)),
                ("Total_Tag_Tree_Verify_C", models.IntegerField(blank=True, null=True)),
                (
                    "Total_Tag_Tree_Non_Verify_C",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Total_block_plantation_Verify_C",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Total_block_plantation_Non_Verify_C",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteVisitCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SiteVisitCount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TotalNumberOfPlantations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TotalPlantations", models.IntegerField()),
            ],
        ),
    ]
