# Generated by Django 4.2.5 on 2025-02-11 15:38

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portaldash", "0001_initial"),
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockPlantationAdress",
            fields=[
                (
                    "BlockPlantation",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("DISTRICT_C", models.CharField(max_length=100)),
                ("BLOCK_CODE", models.CharField(max_length=100)),
                ("GP_FINAL_C", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Block Plantation Address",
                "verbose_name_plural": "Block Plantation Addresses",
            },
        ),
        migrations.CreateModel(
            name="ConditionOpsations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Condition", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="gov_department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GovPlantationAdress",
            fields=[
                (
                    "Plant_id_gov",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("DISTRICT_C", models.CharField(max_length=100)),
                ("BLOCK_CODE", models.CharField(max_length=100)),
                ("GP_FINAL_C", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Government Plantation Address",
                "verbose_name_plural": "Government Plantation Addresses",
            },
        ),
        migrations.CreateModel(
            name="land_ownershipby_gov_ngo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "land_ownership",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NgoPlantationAdress",
            fields=[
                (
                    "Plant_id_ngo",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("DISTRICT_C", models.CharField(max_length=100)),
                ("BLOCK_CODE", models.CharField(max_length=100)),
                ("GP_FINAL_C", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "NGO Plantation Address",
                "verbose_name_plural": "NGO Plantation Addresses",
            },
        ),
        migrations.CreateModel(
            name="OTP_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_phone", models.CharField(max_length=10)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiration_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OwnershipOpsations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ownership", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("District", models.CharField(max_length=20)),
                ("Block", models.CharField(max_length=20)),
                ("GramPanchayat", models.CharField(max_length=50)),
                ("WardNumber", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Plant Name")),
                (
                    "synonyms",
                    models.TextField(blank=True, verbose_name="Plant Synonyms"),
                ),
                (
                    "hindi_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Plant Hindi Name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.Plant.get_unique_image_path,
                        verbose_name="Plant Image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="plantation_bygov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plantation_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("plantation_height", models.FloatField(blank=True, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_long", models.FloatField(blank=True, null=True)),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.plantation_bygov.get_unique_image_path,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.plantation_bygov.get_unique_image_path,
                    ),
                ),
                ("status", models.BooleanField(blank=True, default=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gov_block",
                        to="portaldash.blocklist",
                    ),
                ),
                (
                    "dict_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gov_dict",
                        to="portaldash.districtlist",
                    ),
                ),
                (
                    "gov_department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gov_department_id",
                        to="api.gov_department",
                    ),
                ),
                (
                    "gp_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gov_gp",
                        to="portaldash.gpfinallist",
                    ),
                ),
                (
                    "land_ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_ownership_bygov",
                        to="api.land_ownershipby_gov_ngo",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_user_for_govsubmittedby",
                        to="account.tempuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="plantation_byngo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plantation_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("plantation_height", models.FloatField(blank=True, null=True)),
                ("ngo_name", models.CharField(blank=True, max_length=100, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_long", models.FloatField(blank=True, null=True)),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.plantation_byngo.get_unique_image_path,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.plantation_byngo.get_unique_image_path,
                    ),
                ),
                ("status", models.BooleanField(blank=True, default=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_block",
                        to="portaldash.blocklist",
                    ),
                ),
                (
                    "dict_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_dict",
                        to="portaldash.districtlist",
                    ),
                ),
                (
                    "gp_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_gp",
                        to="portaldash.gpfinallist",
                    ),
                ),
                (
                    "land_ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_ownership_byngo",
                        to="api.land_ownershipby_gov_ngo",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_user_for_ngosubmittedby",
                        to="account.tempuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="plantation_bypvt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plantation_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("plantation_height", models.FloatField(blank=True, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_long", models.FloatField(blank=True, null=True)),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.plantation_bypvt.get_unique_image_path,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.plantation_bypvt.get_unique_image_path,
                    ),
                ),
                ("status", models.BooleanField(blank=True, default=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvt_block",
                        to="portaldash.blocklist",
                    ),
                ),
                (
                    "dict_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvt_dict",
                        to="portaldash.districtlist",
                    ),
                ),
                (
                    "gp_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvt_gp",
                        to="portaldash.gpfinallist",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_user_for_pvtsubmittedby",
                        to="account.tempuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plantation_type_name",
                    models.CharField(default=False, max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PvtPlantationAdress",
            fields=[
                (
                    "Plant_id_pvt",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("DISTRICT_C", models.CharField(max_length=100)),
                ("BLOCK_CODE", models.CharField(max_length=100)),
                ("GP_FINAL_C", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Private Plantation Address",
                "verbose_name_plural": "Private Plantation Addresses",
            },
        ),
        migrations.CreateModel(
            name="registration_role_department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_dep_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TempDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Village_Name", models.CharField(max_length=30)),
                ("Plant_Height", models.FloatField(blank=True, null=True)),
                ("Height_Unit", models.CharField(default="feet", max_length=10)),
                ("Location_Lat", models.CharField(max_length=20)),
                ("Location_Long", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ConditionInfo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ConditionByIntemp",
                        to="api.conditionopsations",
                    ),
                ),
                (
                    "OwnershipInfo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OwnershipByIntemp",
                        to="api.ownershipopsations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TreeImages",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TreeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TreeName", models.CharField(max_length=50)),
                ("BotanicalName", models.CharField(max_length=50)),
                ("Family", models.CharField(max_length=50)),
                ("FlowerColor", models.CharField(max_length=20)),
                ("FruitSeason", models.CharField(max_length=20)),
                ("FlowerSeason", models.CharField(max_length=20)),
                ("ShortDescription", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TreeMoreDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Girth", models.FloatField()),
                ("Girth_Unit", models.CharField(default="feet", max_length=10)),
                ("Age", models.FloatField()),
                ("Age_Unit", models.CharField(default="Months", max_length=10)),
                ("TreeCanopy", models.FloatField()),
                (
                    "TreeCanopy_Unit",
                    models.CharField(default="Sq. feet", max_length=10),
                ),
                (
                    "TempDatabase_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TempDatabase",
                        to="api.tempdatabase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreeLocationsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Place_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PlaceDetails",
                        to="api.placedetails",
                    ),
                ),
                (
                    "TreeData_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TreeDetails",
                        to="api.tempdatabase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreeData",
            fields=[
                (
                    "QrCode",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Girth_m", models.FloatField()),
                ("Height_m", models.FloatField()),
                ("Age_y", models.IntegerField()),
                ("TreeCanopy_m", models.FloatField()),
                ("Location_Lat", models.CharField(max_length=20)),
                ("Location_Long", models.CharField(max_length=20)),
                ("Remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ConditionInfo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ConditionBy",
                        to="api.conditionopsations",
                    ),
                ),
                (
                    "TreeImage_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TreeImageUriBy",
                        to="api.treeimage",
                    ),
                ),
                (
                    "TreeInfo_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TreeInfoBy",
                        to="api.treeinfo",
                    ),
                ),
                (
                    "ownershipinfo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OwnershipBy",
                        to="api.ownershipopsations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TempStorageCertificateInfo",
            fields=[
                ("user_id", models.CharField(max_length=10)),
                (
                    "certificate_id",
                    models.CharField(
                        default=api.models.generate_unique_certificate_id,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "selfi_image",
                    models.ImageField(
                        upload_to=api.models.TempStorageCertificateInfo.get_unique_image_path
                    ),
                ),
                ("certificate_holder_name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plantation_id_bygov",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantation_id_bygov_provided",
                        to="api.plantation_bygov",
                    ),
                ),
                (
                    "plantation_id_byngo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantation_id_byngo_provided",
                        to="api.plantation_byngo",
                    ),
                ),
                (
                    "plantation_id_bypvt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantation_id_bypvt_provided",
                        to="api.plantation_bypvt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tempdatabase",
            name="TreeImage_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TreeImageUriByIntemp",
                to="api.treeimage",
            ),
        ),
        migrations.AddField(
            model_name="tempdatabase",
            name="TreeInfo_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TreeInfoFortemp",
                to="api.treeinfo",
            ),
        ),
        migrations.CreateModel(
            name="reward_storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plantation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewordfor_plantation_bypvt",
                        to="api.plantation_bypvt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivateOwnerShipDeatils",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Contact_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "TreeData_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TreedataBy",
                        to="api.treedata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateStorage",
            fields=[
                (
                    "certificate_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "certificate_image",
                    models.ImageField(upload_to="images/certificate_image/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_id_certificate",
                        to="account.tempuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockPlantation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_list", models.TextField()),
                (
                    "image1_block_planation",
                    models.ImageField(
                        default="NOT_AVILABE",
                        upload_to=api.models.BlockPlantation.get_unique_image_path,
                    ),
                ),
                ("location_lat", models.FloatField()),
                ("location_long", models.FloatField()),
                ("number_of_plants", models.CharField(max_length=5)),
                ("plantationArea", models.CharField(max_length=3)),
                ("planta_name_text", models.TextField()),
                ("status", models.BooleanField(blank=True, default=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_block",
                        to="portaldash.blocklist",
                    ),
                ),
                (
                    "dict_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_dict",
                        to="portaldash.districtlist",
                    ),
                ),
                (
                    "goverment_departmet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockplanat_goverment_departmet",
                        to="api.gov_department",
                    ),
                ),
                (
                    "gp_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_gp",
                        to="portaldash.gpfinallist",
                    ),
                ),
                (
                    "land_ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockplanat_land_ownership",
                        to="api.land_ownershipby_gov_ngo",
                    ),
                ),
                (
                    "plantation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockplanatation_plantatin_type",
                        to="api.plantationtype",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockplanatation_submittedby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
