# Generated by Django 5.1 on 2025-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrcodeVisiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qrcode', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
