# Generated by Django 5.1 on 2025-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicqrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodevisiter',
            name='qrcode',
            field=models.CharField(max_length=255),
        ),
    ]
